### ISSUE TITLE
Recursive Params?

### ISSUE THREAD

**Issue by gkoberger** [lakenen/node-append-query#1]
Any chance of supporting converting `{user: {name: 'john'}}` to `?user[name]=john`?

Great package; thanks!

**Comment by lakenen** [comment]
Thanks @gkoberger! I'm glad you found it useful. I just took a stab at adding recursive serialization (see https://github.com/lakenen/node-append-query/pull/2). Let me know what you think!

**Comment by gkoberger** [comment]
Awesome! That was super quick; thanks!

**Comment by lakenen** [comment]
Landed in 1.1.0 on npm!
