### ISSUE TITLE
Null values in query objects cause lib to throw

### ISSUE THREAD

**Issue by nason** [lakenen/node-append-query#5]
```
var appendQuery = require("append-query");
var foo = appendQuery('http://bar.com/', { baz: null });
```

I would expect `foo` to equal: `http://bar.com/?baz`
Instead this error is thrown: `TypeError: Cannot convert undefined or null to object`

**Comment by lakenen** [comment]
Sorry about the delay! Just released v2.0.0 to fix this issue.

**Comment by nason** [comment]
Thanks so much @lakenen! I'll test this out soon

**Comment by nason** [comment]
Working great! Thanks again @lakenen
